FROM python:3-alpine

# create non-root user
RUN addgroup -S nonroot && adduser -S nonroot -G nonroot

# configure logging
ENV NUT_PROMETEUS_LOG_DIR /var/log/nut-monitor
RUN mkdir -p $NUT_PROMETEUS_LOG_DIR ; \
    chown -R nonroot:nonroot $NUT_PROMETEUS_LOG_DIR

# configure application home
ENV NUT_PROMETEUS_HOME /app
RUN mkdir -p $NUT_PROMETEUS_HOME; \
    chown -R nonroot:nonroot $NUT_PROMETEUS_HOME

USER nonroot
WORKDIR $NUT_PROMETEUS_HOME

# create virtual environment
ENV VIRTUAL_ENV $NUT_PROMETEUS_HOME/venv
RUN pip install --user --no-cache-dir virtualenv ; \
    python -m venv $VIRTUAL_ENV

# install dependencies
COPY --chown=nonroot:nonroot requirements-prometeus.txt requirements.txt
RUN source $VIRTUAL_ENV/bin/activate ; \
    pip install --no-cache-dir -r requirements.txt

# copy source code
COPY --chown=nonroot:nonroot src/config/ config/
COPY --chown=nonroot:nonroot src/prometeus.py .
COPY --chown=nonroot:nonroot src/nutclient.py .
COPY --chown=nonroot:nonroot src/nutsock.py .
COPY --chown=nonroot:nonroot src/nutvartypes.py .

ENV NUT_PROMETEUS_PORT 8000

# Add a health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:${NUT_PROMETEUS_PORT}/metrics || exit 1

RUN <<'EOT' cat > run && chmod 0755 run
#!/bin/sh

source $VIRTUAL_ENV/bin/activate
exec python ./prometeus.py
"
EOT

CMD ["./run"]
