{
 "title": "UPS Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "upsname",
    "label": "UPS",
    "query": {
     "query": "label_values(upsmon_ups_info,ups)"
    }
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Beeper Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_ups_beeper_status{ups=\"$upsname\"} == 1"
    }
   ]
  },
  {
   "title": "UPS Load (W)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_ups_realpower{ups=\"$upsname\"} or upsmon_calc_ups_realpower{ups=\"$upsname\"}",
     "legendFormat": "$upsname"
    }
   ]
  },
  {
   "title": "UPS Load %",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_ups_load{ups=\"$upsname\"}",
     "legendFormat": "$upsname"
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsmon_calc_status_ups{ups=\"$upsname\"} == 1"
    }
   ]
  },
  {
   "title": "Battery Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_calc_status_battery{ups=\"$upsname\"} == 1"
    }
   ]
  },
  {
   "title": "Battery Charge %",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_battery_charge{ups=\"$upsname\"}",
     "legendFormat": "$upsname"
    }
   ]
  },
  {
   "title": "Battery Remains",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_battery_runtime{ups=\"$upsname\"}",
     "legendFormat": "$upsname"
    }
   ]
  },
  {
   "title": "Battery Voltage (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_battery_voltage{ups=\"$upsname\"}",
     "legendFormat": "$upsname"
    }
   ]
  },
  {
   "title": "Last Transfer Reason",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_input_transfer_reason_info{ups=\"$upsname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input voltage (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_input_voltage{ups=\"$upsname\"}",
     "legendFormat": "$upsname"
    }
   ]
  },
  {
   "title": "Mfr.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsmon_ups_info{ups=\"$upsname\"} == 1"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsmon_ups_info{ups=\"$upsname\"} == 1"
    }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsmon_ups_info{ups=\"$upsname\"} == 1"
    }
   ]
  },
  {
   "title": "UPS Alarm",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_ups_alarm_info{ups=\"$upsname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Test Result",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsmon_ups_test_result_info{ups=\"$upsname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "upsmon_battery_voltage{ups=\"$upsname\"}",
     "legendFormat": "actual"
    },
    {
     "expr": "upsmon_battery_voltage_nominal{ups=\"$upsname\"}",
     "legendFormat": "nominal"
    }
   ]
  },
  {
   "title": "Charge %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "upsmon_battery_charge{ups=\"$upsname\"}",
     "legendFormat": "actual"
    },
    {
     "expr": "upsmon_battery_charge_warning{ups=\"$upsname\"}",
     "legendFormat": "warning"
    },
    {
     "expr": "upsmon_battery_charge_low{ups=\"$upsname\"}",
     "legendFormat": "low"
    }
   ]
  },
  {
   "title": "Remains (T)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "upsmon_battery_runtime{ups=\"$upsname\"}",
     "legendFormat": "actual"
    },
    {
     "expr": "upsmon_battery_runtime_low{ups=\"$upsname\"}",
     "legendFormat": "low"
    }
   ]
  },
  { "title": "Input and Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Input voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "upsmon_input_voltage{ups=\"$upsname\"}",
     "legendFormat": "actual"
    },
    {
     "expr": "upsmon_input_voltage_nominal{ups=\"$upsname\"}",
     "legendFormat": "nominal"
    }
   ]
  },
  {
   "title": "UPS Load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "upsmon_ups_load{ups=\"$upsname\"}",
     "legendFormat": "actual"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "UPS Load (W)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "avg_over_time(upsmon_ups_power{ups=\"$upsname\"}[1h])",
     "legendFormat": "$upsname"
    }
   ]
  },
  {
   "title": "UPS Load (W)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum_over_time(upsmon_ups_power{ups=\"$upsname\"}[1d]) / count_over_time(upsmon_ups_power{ups=\"$upsname\"}[1h])",
     "legendFormat": "$upsname"
    }
   ]
  },
  {
   "title": "UPS Load (W)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum_over_time(upsmon_ups_power{ups=\"$upsname\"}[1d]) / count_over_time(upsmon_ups_power{ups=\"$upsname\"}[1h])",
     "legendFormat": "$upsname"
    }
   ]
  },
  {
   "title": "Total power usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(upsmon_ups_power{ups=\"$upsname\"}[1h]) / (count_over_time(upsmon_ups_power{ups=\"$upsname\"}[1m]) * 60)",
     "legendFormat": "Consumed (last hour)"
    },
    {
     "expr": "sum_over_time(upsmon_ups_power{ups=\"$upsname\"}[1d]) / (count_over_time(upsmon_ups_power{ups=\"$upsname\"}[1m]) * 60)",
     "legendFormat": "Consumed (last day)"
    },
    {
     "expr": "sum_over_time(upsmon_ups_power{ups=\"$upsname\"}[1w]) / (count_over_time(upsmon_ups_power{ups=\"$upsname\"}[1m]) * 60)",
     "legendFormat": "Consumed (last week)"
    },
    {
     "expr": "sum_over_time(upsmon_ups_power{ups=\"$upsname\"}[30d]) / (count_over_time(upsmon_ups_power{ups=\"$upsname\"}[1m]) * 60)",
     "legendFormat": "Consumed (last month)"
    }
   ]
  }
 ]
}